all: example infector

example: example/hello_world
	gcc -Wall -Wextra -Wpedantic -o example/hello_world example/hello_world.c

infector:
	gcc -Wall -Wextra -Wpedantic -o build/infector src/infector.c
